
CREATE DATABASE pp_14_06_29 CHARACTER SET 'utf8';
use pp_14_06_29;
CREATE TABLE udp_11 (sn INT PRIMARY KEY AUTO_INCREMENT, daytime datetime, info text) DEFAULT CHARSET=utf8;
CREATE TABLE udp_15 (sn INT PRIMARY KEY AUTO_INCREMENT, daytime datetime, info text) DEFAULT CHARSET=utf8;

