
use pp_format;

CREATE TABLE IF NOT EXISTS format_14_07_26(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_14_06_29(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_14_06_21(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_14_05_24(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_14_04_19(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_14_03_15(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_14_02_15(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_14_01_18(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;


