
use pp_format;

CREATE TABLE IF NOT EXISTS format_price_2015_02_07(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_price_2015_01_17(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_price_2014_12_20(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_price_2014_11_15(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_price_2014_10_18(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_price_2014_09_20(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_price_2014_08_16(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_price_2014_07_26(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_price_2014_06_29(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_price_2014_06_21(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_price_2014_05_24(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_price_2014_04_19(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_price_2014_03_15(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_price_2014_02_15(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_price_2014_01_18(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, price INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS format_number_2015_02_07(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, number INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_number_2015_01_17(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, number INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_number_2014_12_20(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, number INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_number_2014_11_15(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, number INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_number_2014_10_18(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, number INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_number_2014_09_20(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, number INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_number_2014_08_16(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, number INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_number_2014_07_26(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, number INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_number_2014_06_29(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, number INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_number_2014_06_21(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, number INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_number_2014_05_24(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, number INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_number_2014_04_19(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, number INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_number_2014_03_15(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, number INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_number_2014_02_15(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, number INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_number_2014_01_18(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, number INT DEFAULT 0, count INT DEFAULT 0, INDEX(datetime)) DEFAULT CHARSET=utf8;


