#############################################################################
# Generated by PAGE version 4.2.5
# in conjunction with Tcl version 8.6
#    Jun. 13, 2014 02:47:48 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top36
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 1
    }
    set site_3_0 $base.fra37
    set site_4_0 $site_3_0.fra86
    set site_4_0 $site_3_0.fra93
    set site_5_0 $site_4_0.fra127
    set site_3_0 $base.fra39
    set site_4_0 $site_3_0.fra85
    set site_5_0 $site_4_0.fra136
    set site_5_0 $site_4_0.fra148
    set site_4_0 $site_3_0.fra96
    set site_5_0 $site_4_0.fra129
    set site_5_0 $site_4_0.fra132
    set site_5_0 $site_4_0.fra133
    set site_3_0 $base.fra41
    set site_4_0 $site_3_0.fra84
    set site_5_0 $site_4_0.fra36
    set site_4_0 $site_3_0.fra97
    set site_5_0 $site_4_0.fra138
    set site_5_0 $site_4_0.fra140
    set site_5_0 $site_4_0.fra141
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
            proc_login
            proc_channel
            proc_image_price
            proc_image_decode
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#
#############################################################################
## Procedure:  proc_login

proc ::proc_login {} {

}
#############################################################################
## Procedure:  proc_channel

proc ::proc_channel {} {

}
#############################################################################
## Procedure:  proc_image_price

proc ::proc_image_price {} {

}
#############################################################################
## Procedure:  proc_image_decode

proc ::proc_image_decode {} {

}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow. {base} {
    if {$base == ""} {
        set base .
    }
    ###################
    # CREATING WIDGETS
    ###################
    wm focusmodel $top passive
    wm geometry $top 200x200+175+175; update
    wm maxsize $top 1924 1062
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm withdraw $top
    wm title $top "page"
    bindtags $top "$top Page all"
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top36 {base} {
    if {$base == ""} {
        set base .top36
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 659x673+580+151; update
    wm maxsize $top 1924 1062
    wm minsize $top 126 10
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Console"
    vTcl:DefineAlias "$top" "Console" vTcl:Toplevel:WidgetProc "" 1
    bindtags $top "$top Toplevel all _TopLevel"
    ttk::style configure Frame -background #d9d9d9
    ttk::style configure Frame -foreground #000000
    ttk::style configure Frame -font TkDefaultFont
    frame $top.fra37 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 135 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 595 
    vTcl:DefineAlias "$top.fra37" "Frame1" vTcl:WidgetProc "Console" 1
    set site_3_0 $top.fra37
    frame $site_3_0.fra86 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 95 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 345 
    vTcl:DefineAlias "$site_3_0.fra86" "Frame6" vTcl:WidgetProc "Console" 1
    set site_4_0 $site_3_0.fra86
    entry $site_4_0.ent87 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify right \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent87" "input_bidno" vTcl:WidgetProc "Console" 1
    entry $site_4_0.ent88 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify right \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent88" "input_passwd" vTcl:WidgetProc "Console" 1
    button $site_4_0.but89 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text 登录 
    vTcl:DefineAlias "$site_4_0.but89" "button_login" vTcl:WidgetProc "Console" 1
    bind $site_4_0.but89 <Button-1> {
        proc_login
    }
    label $site_4_0.lab91 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 账号 
    vTcl:DefineAlias "$site_4_0.lab91" "Label7" vTcl:WidgetProc "Console" 1
    label $site_4_0.lab92 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 密码 
    vTcl:DefineAlias "$site_4_0.lab92" "Label8" vTcl:WidgetProc "Console" 1
    checkbutton $site_4_0.che152 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 使用组2 -variable che90 
    vTcl:DefineAlias "$site_4_0.che152" "check_use_group2" vTcl:WidgetProc "Console" 1
    place $site_4_0.ent87 \
        -in $site_4_0 -x 110 -y 10 -width 104 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent88 \
        -in $site_4_0 -x 110 -y 50 -width 104 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but89 \
        -in $site_4_0 -x 250 -y 50 -width 75 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab91 \
        -in $site_4_0 -x 40 -y 10 -anchor nw -bordermode ignore 
    place $site_4_0.lab92 \
        -in $site_4_0 -x 40 -y 50 -anchor nw -bordermode ignore 
    place $site_4_0.che152 \
        -in $site_4_0 -x 250 -y 10 -anchor nw -bordermode ignore 
    frame $site_3_0.fra93 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 95 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 185 
    vTcl:DefineAlias "$site_3_0.fra93" "Frame7" vTcl:WidgetProc "Console" 1
    set site_4_0 $site_3_0.fra93
    frame $site_4_0.fra127 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 55 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 85 
    vTcl:DefineAlias "$site_4_0.fra127" "Frame10" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra127
    message $site_5_0.mes128 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 未登录 \
        -width 67 
    vTcl:DefineAlias "$site_5_0.mes128" "output_login_status" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes128 \
        -in $site_5_0 -x 10 -y 10 -width 67 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra127 \
        -in $site_4_0 -x 50 -y 20 -width 85 -height 55 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra86 \
        -in $site_3_0 -x 230 -y 20 -width 345 -height 95 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra93 \
        -in $site_3_0 -x 20 -y 20 -width 185 -height 95 -anchor nw \
        -bordermode ignore 
    frame $top.fra39 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 215 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 595 
    vTcl:DefineAlias "$top.fra39" "Frame3" vTcl:WidgetProc "Console" 1
    set site_3_0 $top.fra39
    frame $site_3_0.fra85 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 175 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 235 
    vTcl:DefineAlias "$site_3_0.fra85" "Frame4" vTcl:WidgetProc "Console" 1
    set site_4_0 $site_3_0.fra85
    entry $site_4_0.ent107 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent107" "input_ajust_channel" vTcl:WidgetProc "Console" 1
    button $site_4_0.but108 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text 调整通道数 
    vTcl:DefineAlias "$site_4_0.but108" "button_channel" vTcl:WidgetProc "Console" 1
    bind $site_4_0.but108 <Button-1> {
        proc_channel
    }
    label $site_4_0.lab109 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 计划通道数 
    vTcl:DefineAlias "$site_4_0.lab109" "Label5" vTcl:WidgetProc "Console" 1
    label $site_4_0.lab110 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$site_4_0.lab110" "Label6" vTcl:WidgetProc "Console" 1
    frame $site_4_0.fra136 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 95 
    vTcl:DefineAlias "$site_4_0.fra136" "Frame14" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra136
    message $site_5_0.mes137 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 0 \
        -width 57 
    vTcl:DefineAlias "$site_5_0.mes137" "output_goal_channel" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes137 \
        -in $site_5_0 -x 20 -y 10 -width 57 -height 15 -anchor nw \
        -bordermode ignore 
    frame $site_4_0.fra148 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 95 
    vTcl:DefineAlias "$site_4_0.fra148" "Frame18" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra148
    message $site_5_0.mes149 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 0 \
        -width 57 
    vTcl:DefineAlias "$site_5_0.mes149" "output_current_channel" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes149 \
        -in $site_5_0 -x 20 -y 10 -width 57 -height 15 -anchor nw \
        -bordermode ignore 
    label $site_4_0.lab150 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 可用通道数 
    vTcl:DefineAlias "$site_4_0.lab150" "Label14" vTcl:WidgetProc "Console" 1
    place $site_4_0.ent107 \
        -in $site_4_0 -x 30 -y 120 -width 94 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but108 \
        -in $site_4_0 -x 140 -y 120 -width 79 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab109 \
        -in $site_4_0 -x 150 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.lab110 \
        -in $site_4_0 -x 30 -y 60 -anchor nw -bordermode ignore 
    place $site_4_0.fra136 \
        -in $site_4_0 -x 30 -y 20 -width 95 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra148 \
        -in $site_4_0 -x 30 -y 70 -width 95 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab150 \
        -in $site_4_0 -x 150 -y 80 -anchor nw -bordermode ignore 
    frame $site_3_0.fra96 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 175 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 295 
    vTcl:DefineAlias "$site_3_0.fra96" "Frame8" vTcl:WidgetProc "Console" 1
    set site_4_0 $site_3_0.fra96
    label $site_4_0.lab98 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 变价时间 
    vTcl:DefineAlias "$site_4_0.lab98" "Label2" vTcl:WidgetProc "Console" 1
    label $site_4_0.lab99 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 系统时间 
    vTcl:DefineAlias "$site_4_0.lab99" "Label3" vTcl:WidgetProc "Console" 1
    label $site_4_0.lab100 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 当前价格 
    vTcl:DefineAlias "$site_4_0.lab100" "Label4" vTcl:WidgetProc "Console" 1
    frame $site_4_0.fra129 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_4_0.fra129" "Frame11" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra129
    message $site_5_0.mes130 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 00:00:00 \
        -width 67 
    vTcl:DefineAlias "$site_5_0.mes130" "output_change_time" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes130 \
        -in $site_5_0 -x 30 -y 10 -width 67 -height 15 -anchor nw \
        -bordermode ignore 
    frame $site_4_0.fra132 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_4_0.fra132" "Frame12" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra132
    message $site_5_0.mes134 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 00:00:00 \
        -width 67 
    vTcl:DefineAlias "$site_5_0.mes134" "output_system_time" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes134 \
        -in $site_5_0 -x 30 -y 10 -width 67 -height 15 -anchor nw \
        -bordermode ignore 
    frame $site_4_0.fra133 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_4_0.fra133" "Frame13" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra133
    message $site_5_0.mes135 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 0 \
        -width 67 
    vTcl:DefineAlias "$site_5_0.mes135" "output_current_price" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes135 \
        -in $site_5_0 -x 30 -y 10 -width 67 -height 15 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab98 \
        -in $site_4_0 -x 40 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.lab99 \
        -in $site_4_0 -x 40 -y 80 -anchor nw -bordermode ignore 
    place $site_4_0.lab100 \
        -in $site_4_0 -x 40 -y 130 -anchor nw -bordermode ignore 
    place $site_4_0.fra129 \
        -in $site_4_0 -x 130 -y 20 -width 125 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra132 \
        -in $site_4_0 -x 130 -y 70 -width 125 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra133 \
        -in $site_4_0 -x 130 -y 120 -width 125 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra85 \
        -in $site_3_0 -x 340 -y 20 -width 235 -height 175 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra96 \
        -in $site_3_0 -x 20 -y 20 -width 295 -height 175 -anchor nw \
        -bordermode ignore 
    frame $top.fra41 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 235 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 595 
    vTcl:DefineAlias "$top.fra41" "Frame5" vTcl:WidgetProc "Console" 1
    set site_3_0 $top.fra41
    frame $site_3_0.fra84 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 195 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 345 
    vTcl:DefineAlias "$site_3_0.fra84" "Frame2" vTcl:WidgetProc "Console" 1
    set site_4_0 $site_3_0.fra84
    entry $site_4_0.ent123 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify right \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent123" "input_image_price" vTcl:WidgetProc "Console" 1
    entry $site_4_0.ent124 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify right \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent124" "input_image_decode" vTcl:WidgetProc "Console" 1
    button $site_4_0.but125 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text 请求图形码 
    vTcl:DefineAlias "$site_4_0.but125" "button_image_price" vTcl:WidgetProc "Console" 1
    bind $site_4_0.but125 <Button-1> {
        proc_image_price
    }
    button $site_4_0.but126 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text 打码并出价 
    vTcl:DefineAlias "$site_4_0.but126" "button_image_decode" vTcl:WidgetProc "Console" 1
    bind $site_4_0.but126 <Button-1> {
        proc_image_decode
    }
    frame $site_4_0.fra36 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 45 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 105 
    vTcl:DefineAlias "$site_4_0.fra36" "Frame19" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra36
    message $site_5_0.mes38 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify center \
        -text 请求价格 -width 70 
    vTcl:DefineAlias "$site_5_0.mes38" "output_last_price" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes38 \
        -in $site_5_0 -x 20 -y 10 -anchor nw -bordermode ignore 
    label $site_4_0.lab36 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 图片 
    vTcl:DefineAlias "$site_4_0.lab36" "output_image" vTcl:WidgetProc "Console" 1
    place $site_4_0.ent123 \
        -in $site_4_0 -x 150 -y 50 -width 84 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent124 \
        -in $site_4_0 -x 150 -y 120 -width 84 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but125 \
        -in $site_4_0 -x 250 -y 50 -width 81 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but126 \
        -in $site_4_0 -x 250 -y 120 -width 81 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra36 \
        -in $site_4_0 -x 20 -y 40 -width 105 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab36 \
        -in $site_4_0 -x 10 -y 110 -width 127 -height 53 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra97 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 195 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 185 
    vTcl:DefineAlias "$site_3_0.fra97" "Frame9" vTcl:WidgetProc "Console" 1
    set site_4_0 $site_3_0.fra97
    label $site_4_0.lab114 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 第一次 
    vTcl:DefineAlias "$site_4_0.lab114" "Label9" vTcl:WidgetProc "Console" 1
    label $site_4_0.lab115 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 第二次 
    vTcl:DefineAlias "$site_4_0.lab115" "Label10" vTcl:WidgetProc "Console" 1
    label $site_4_0.lab116 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 第三次 
    vTcl:DefineAlias "$site_4_0.lab116" "Label11" vTcl:WidgetProc "Console" 1
    frame $site_4_0.fra138 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 95 
    vTcl:DefineAlias "$site_4_0.fra138" "Frame15" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra138
    message $site_5_0.mes139 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 0 \
        -width 57 
    vTcl:DefineAlias "$site_5_0.mes139" "output_first_price" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes139 \
        -in $site_5_0 -x 20 -y 10 -width 57 -height 15 -anchor nw \
        -bordermode ignore 
    frame $site_4_0.fra140 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 95 
    vTcl:DefineAlias "$site_4_0.fra140" "Frame16" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra140
    message $site_5_0.mes142 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 0 \
        -width 57 
    vTcl:DefineAlias "$site_5_0.mes142" "output_second_price" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes142 \
        -in $site_5_0 -x 20 -y 10 -width 57 -height 15 -anchor nw \
        -bordermode ignore 
    frame $site_4_0.fra141 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 95 
    vTcl:DefineAlias "$site_4_0.fra141" "Frame17" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra141
    message $site_5_0.mes143 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 0 \
        -width 57 
    vTcl:DefineAlias "$site_5_0.mes143" "output_third_price" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes143 \
        -in $site_5_0 -x 20 -y 10 -width 57 -height 15 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab114 \
        -in $site_4_0 -x 10 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.lab115 \
        -in $site_4_0 -x 10 -y 90 -anchor nw -bordermode ignore 
    place $site_4_0.lab116 \
        -in $site_4_0 -x 10 -y 150 -anchor nw -bordermode ignore 
    place $site_4_0.fra138 \
        -in $site_4_0 -x 70 -y 20 -width 95 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra140 \
        -in $site_4_0 -x 70 -y 80 -width 95 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra141 \
        -in $site_4_0 -x 70 -y 140 -width 95 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra84 \
        -in $site_3_0 -x 230 -y 20 -width 345 -height 195 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra97 \
        -in $site_3_0 -x 20 -y 20 -width 185 -height 195 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra37 \
        -in $top -x 30 -y 30 -width 595 -height 135 -anchor nw \
        -bordermode ignore 
    place $top.fra39 \
        -in $top -x 30 -y 180 -width 595 -height 215 -anchor nw \
        -bordermode ignore 
    place $top.fra41 \
        -in $top -x 30 -y 410 -width 595 -height 235 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top36

