#############################################################################
# Generated by PAGE version 4.2.5
# in conjunction with Tcl version 8.6
#    Jun. 17, 2014 06:50:07 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top36
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 0
    }
    set site_3_0 $base.fra37
    set site_4_0 $site_3_0.fra86
    set site_4_0 $site_3_0.fra93
    set site_5_0 $site_4_0.fra127
    set site_3_0 $base.fra39
    set site_4_0 $site_3_0.fra96
    set site_5_0 $site_4_0.fra129
    set site_5_0 $site_4_0.fra132
    set site_5_0 $site_4_0.fra133
    set site_4_0 $site_3_0.fra47
    set site_5_0 $site_4_0.fra49
    set site_5_0 $site_4_0.fra50
    set site_5_0 $site_4_0.fra36
    set site_4_0 $site_3_0.fra48
    set site_5_0 $site_4_0.fra51
    set site_5_0 $site_4_0.fra52
    set site_5_0 $site_4_0.fra37
    set site_3_0 $base.fra41
    set site_4_0 $site_3_0.fra84
    set site_5_0 $site_4_0.fra36
    set site_5_0 $site_4_0.fra37
    set site_4_0 $site_3_0.fra97
    set site_5_0 $site_4_0.fra138
    set site_5_0 $site_4_0.fra140
    set site_5_0 $site_4_0.fra141
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
            proc_login
            proc_channel
            proc_image_price
            proc_image_decode
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#
#############################################################################
## Procedure:  proc_login

proc ::proc_login {} {

}
#############################################################################
## Procedure:  proc_channel

proc ::proc_channel {} {

}
#############################################################################
## Procedure:  proc_image_price

proc ::proc_image_price {} {

}
#############################################################################
## Procedure:  proc_image_decode

proc ::proc_image_decode {p1} {

}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow. {base} {
    if {$base == ""} {
        set base .
    }
    ###################
    # CREATING WIDGETS
    ###################
    wm focusmodel $top passive
    wm geometry $top 200x200+75+75; update
    wm maxsize $top 1924 1062
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm withdraw $top
    wm title $top "page"
    bindtags $top "$top Page all"
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top36 {base} {
    if {$base == ""} {
        set base .top36
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm withdraw $top
    wm focusmodel $top passive
    wm geometry $top 659x729+306+80; update
    wm maxsize $top 1924 1062
    wm minsize $top 126 10
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm title $top "Console"
    vTcl:DefineAlias "$top" "Console" vTcl:Toplevel:WidgetProc "" 1
    bindtags $top "$top Toplevel all _TopLevel"
    frame $top.fra37 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 145 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 595 
    vTcl:DefineAlias "$top.fra37" "Frame1" vTcl:WidgetProc "Console" 1
    set site_3_0 $top.fra37
    frame $site_3_0.fra86 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 105 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 345 
    vTcl:DefineAlias "$site_3_0.fra86" "Frame6" vTcl:WidgetProc "Console" 1
    set site_4_0 $site_3_0.fra86
    entry $site_4_0.ent87 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify right \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent87" "input_bidno" vTcl:WidgetProc "Console" 1
    entry $site_4_0.ent88 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify right \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent88" "input_passwd" vTcl:WidgetProc "Console" 1
    button $site_4_0.but89 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text 登录 
    vTcl:DefineAlias "$site_4_0.but89" "button_login" vTcl:WidgetProc "Console" 1
    bind $site_4_0.but89 <Button-1> {
        proc_login
    }
    label $site_4_0.lab91 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 账号 
    vTcl:DefineAlias "$site_4_0.lab91" "Label7" vTcl:WidgetProc "Console" 1
    label $site_4_0.lab92 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 密码 
    vTcl:DefineAlias "$site_4_0.lab92" "Label8" vTcl:WidgetProc "Console" 1
    checkbutton $site_4_0.che152 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 使用组2 -variable che90 
    vTcl:DefineAlias "$site_4_0.che152" "check_use_group2" vTcl:WidgetProc "Console" 1
    place $site_4_0.ent87 \
        -in $site_4_0 -x 140 -y 20 -width 84 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent88 \
        -in $site_4_0 -x 140 -y 60 -width 84 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but89 \
        -in $site_4_0 -x 250 -y 60 -width 81 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab91 \
        -in $site_4_0 -x 50 -y 20 -width 40 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab92 \
        -in $site_4_0 -x 50 -y 60 -width 40 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.che152 \
        -in $site_4_0 -x 250 -y 20 -width 81 -height 27 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra93 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 105 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 185 
    vTcl:DefineAlias "$site_3_0.fra93" "Frame7" vTcl:WidgetProc "Console" 1
    set site_4_0 $site_3_0.fra93
    frame $site_4_0.fra127 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 55 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 95 
    vTcl:DefineAlias "$site_4_0.fra127" "Frame10" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra127
    message $site_5_0.mes128 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify center \
        -text 未登录 -width 77 
    vTcl:DefineAlias "$site_5_0.mes128" "output_login_status" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes128 \
        -in $site_5_0 -x 10 -y 10 -width 77 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra127 \
        -in $site_4_0 -x 40 -y 30 -width 95 -height 55 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra86 \
        -in $site_3_0 -x 230 -y 20 -width 345 -height 105 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra93 \
        -in $site_3_0 -x 20 -y 20 -width 185 -height 105 -anchor nw \
        -bordermode ignore 
    frame $top.fra39 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 265 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 595 
    vTcl:DefineAlias "$top.fra39" "Frame3" vTcl:WidgetProc "Console" 1
    set site_3_0 $top.fra39
    frame $site_3_0.fra96 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 225 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 185 
    vTcl:DefineAlias "$site_3_0.fra96" "Frame8" vTcl:WidgetProc "Console" 1
    set site_4_0 $site_3_0.fra96
    label $site_4_0.lab98 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 变价时间 
    vTcl:DefineAlias "$site_4_0.lab98" "Label2" vTcl:WidgetProc "Console" 1
    label $site_4_0.lab99 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 系统时间 
    vTcl:DefineAlias "$site_4_0.lab99" "Label3" vTcl:WidgetProc "Console" 1
    label $site_4_0.lab100 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 当前价格 
    vTcl:DefineAlias "$site_4_0.lab100" "Label4" vTcl:WidgetProc "Console" 1
    frame $site_4_0.fra129 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 85 
    vTcl:DefineAlias "$site_4_0.fra129" "Frame11" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra129
    message $site_5_0.mes130 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 00:00:00 \
        -width 67 
    vTcl:DefineAlias "$site_5_0.mes130" "output_change_time" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes130 \
        -in $site_5_0 -x 10 -y 10 -width 67 -height 15 -anchor nw \
        -bordermode ignore 
    frame $site_4_0.fra132 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 85 
    vTcl:DefineAlias "$site_4_0.fra132" "Frame12" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra132
    message $site_5_0.mes134 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 00:00:00 \
        -width 67 
    vTcl:DefineAlias "$site_5_0.mes134" "output_system_time" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes134 \
        -in $site_5_0 -x 10 -y 10 -width 67 -height 15 -anchor nw \
        -bordermode ignore 
    frame $site_4_0.fra133 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 85 
    vTcl:DefineAlias "$site_4_0.fra133" "Frame13" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra133
    message $site_5_0.mes135 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 0 \
        -width 67 
    vTcl:DefineAlias "$site_5_0.mes135" "output_current_price" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes135 \
        -in $site_5_0 -x 10 -y 10 -width 67 -height 15 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab98 \
        -in $site_4_0 -x 10 -y 40 -anchor nw -bordermode ignore 
    place $site_4_0.lab99 \
        -in $site_4_0 -x 10 -y 110 -anchor nw -bordermode ignore 
    place $site_4_0.lab100 \
        -in $site_4_0 -x 10 -y 180 -anchor nw -bordermode ignore 
    place $site_4_0.fra129 \
        -in $site_4_0 -x 80 -y 30 -width 85 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra132 \
        -in $site_4_0 -x 80 -y 100 -width 85 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra133 \
        -in $site_4_0 -x 80 -y 170 -width 85 -height 35 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra47 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 105 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 345 
    vTcl:DefineAlias "$site_3_0.fra47" "Frame4" vTcl:WidgetProc "Console" 1
    set site_4_0 $site_3_0.fra47
    frame $site_4_0.fra49 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 85 
    vTcl:DefineAlias "$site_4_0.fra49" "Frame18" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra49
    message $site_5_0.mes57 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify center \
        -text {00 : 00} -width 70 
    vTcl:DefineAlias "$site_5_0.mes57" "output_image_current_channel" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes57 \
        -in $site_5_0 -x 10 -y 10 -width 67 -height 15 -anchor nw \
        -bordermode ignore 
    frame $site_4_0.fra50 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 85 
    vTcl:DefineAlias "$site_4_0.fra50" "Frame20" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra50
    message $site_5_0.mes58 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify center \
        -text 0 -width 70 
    vTcl:DefineAlias "$site_5_0.mes58" "output_image_goal_channel" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes58 \
        -in $site_5_0 -x 10 -y 10 -width 67 -height 15 -anchor nw \
        -bordermode ignore 
    entry $site_4_0.ent53 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent53" "input_image_channel" vTcl:WidgetProc "Console" 1
    button $site_4_0.but55 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text 图片通道数 
    vTcl:DefineAlias "$site_4_0.but55" "button_image_channel" vTcl:WidgetProc "Console" 1
    bind $site_4_0.but55 <Button-1> {
        proc_image_channel
    }
    frame $site_4_0.fra36 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 85 
    vTcl:DefineAlias "$site_4_0.fra36" "Frame23" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra36
    message $site_5_0.mes38 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {00 : 00} \
        -width 70 
    vTcl:DefineAlias "$site_5_0.mes38" "output_image_onway_channel" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes38 \
        -in $site_5_0 -x 10 -y 10 -width 67 -height 15 -anchor nw \
        -bordermode ignore 
    button $site_4_0.but36 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text 连图片通道 
    vTcl:DefineAlias "$site_4_0.but36" "button_image_connect" vTcl:WidgetProc "Console" 1
    bind $site_4_0.but36 <Button-1> {
        proc_image_connect
    }
    place $site_4_0.fra49 \
        -in $site_4_0 -x 30 -y 10 -width 85 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra50 \
        -in $site_4_0 -x 30 -y 60 -width 85 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent53 \
        -in $site_4_0 -x 140 -y 60 -width 84 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but55 \
        -in $site_4_0 -x 250 -y 60 -width 81 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra36 \
        -in $site_4_0 -x 140 -y 10 -width 85 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but36 \
        -in $site_4_0 -x 250 -y 10 -width 81 -height 28 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra48 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 105 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 345 
    vTcl:DefineAlias "$site_3_0.fra48" "Frame14" vTcl:WidgetProc "Console" 1
    set site_4_0 $site_3_0.fra48
    frame $site_4_0.fra51 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 85 
    vTcl:DefineAlias "$site_4_0.fra51" "Frame21" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra51
    message $site_5_0.mes59 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify center \
        -text {00 : 00} -width 70 
    vTcl:DefineAlias "$site_5_0.mes59" "output_price_current_channel" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes59 \
        -in $site_5_0 -x 10 -y 10 -width 67 -height 15 -anchor nw \
        -bordermode ignore 
    frame $site_4_0.fra52 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 85 
    vTcl:DefineAlias "$site_4_0.fra52" "Frame22" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra52
    message $site_5_0.mes60 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify center \
        -text 0 -width 70 
    vTcl:DefineAlias "$site_5_0.mes60" "output_price_goal_channel" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes60 \
        -in $site_5_0 -x 10 -y 10 -width 67 -height 15 -anchor nw \
        -bordermode ignore 
    entry $site_4_0.ent54 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify center \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent54" "input_price_channel" vTcl:WidgetProc "Console" 1
    button $site_4_0.but56 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text 价格通道数 
    vTcl:DefineAlias "$site_4_0.but56" "button_price_channel" vTcl:WidgetProc "Console" 1
    bind $site_4_0.but56 <Button-1> {
        proc_price_channel
    }
    frame $site_4_0.fra37 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 85 
    vTcl:DefineAlias "$site_4_0.fra37" "Frame24" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra37
    message $site_5_0.mes39 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {00 : 00} \
        -width 70 
    vTcl:DefineAlias "$site_5_0.mes39" "output_price_onway_channel" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes39 \
        -in $site_5_0 -x 10 -y 10 -width 67 -height 15 -anchor nw \
        -bordermode ignore 
    button $site_4_0.but37 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text 连价格通道 
    vTcl:DefineAlias "$site_4_0.but37" "button_price_connect" vTcl:WidgetProc "Console" 1
    bind $site_4_0.but37 <Button-1> {
        proc_price_connect
    }
    place $site_4_0.fra51 \
        -in $site_4_0 -x 30 -y 10 -width 85 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra52 \
        -in $site_4_0 -x 30 -y 60 -width 85 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent54 \
        -in $site_4_0 -x 140 -y 60 -width 84 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but56 \
        -in $site_4_0 -x 250 -y 60 -width 81 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra37 \
        -in $site_4_0 -x 140 -y 10 -width 85 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but37 \
        -in $site_4_0 -x 250 -y 10 -width 81 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra96 \
        -in $site_3_0 -x 20 -y 20 -width 185 -height 225 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra47 \
        -in $site_3_0 -x 230 -y 20 -width 345 -height 105 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra48 \
        -in $site_3_0 -x 230 -y 140 -width 345 -height 105 -anchor nw \
        -bordermode ignore 
    frame $top.fra41 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 235 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 595 
    vTcl:DefineAlias "$top.fra41" "Frame5" vTcl:WidgetProc "Console" 1
    set site_3_0 $top.fra41
    frame $site_3_0.fra84 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 195 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 345 
    vTcl:DefineAlias "$site_3_0.fra84" "Frame2" vTcl:WidgetProc "Console" 1
    set site_4_0 $site_3_0.fra84
    entry $site_4_0.ent123 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify right \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent123" "input_image_price" vTcl:WidgetProc "Console" 1
    entry $site_4_0.ent124 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black -justify right \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent124" "input_image_decode" vTcl:WidgetProc "Console" 1
    button $site_4_0.but125 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text 请求图形码 
    vTcl:DefineAlias "$site_4_0.but125" "button_image_price" vTcl:WidgetProc "Console" 1
    bind $site_4_0.but125 <Button-1> {
        proc_image_price
    }
    button $site_4_0.but126 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text 打码并出价 
    vTcl:DefineAlias "$site_4_0.but126" "button_image_decode" vTcl:WidgetProc "Console" 1
    bind $site_4_0.but126 <Button-1> {
        proc_image_decode
    }
    frame $site_4_0.fra36 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 95 
    vTcl:DefineAlias "$site_4_0.fra36" "Frame19" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra36
    message $site_5_0.mes38 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify center \
        -text 请求价格 -width 77 
    vTcl:DefineAlias "$site_5_0.mes38" "output_last_price" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes38 \
        -in $site_5_0 -x 10 -y 10 -width 67 -height 15 -anchor nw \
        -bordermode ignore 
    label $site_4_0.lab36 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#a3a3a3} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 图片 
    vTcl:DefineAlias "$site_4_0.lab36" "output_image" vTcl:WidgetProc "Console" 1
    frame $site_4_0.fra37 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 55 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 85 
    vTcl:DefineAlias "$site_4_0.fra37" "Frame25" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra37
    message $site_5_0.mes38 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify center \
        -text {00 : 00} -width 70 
    vTcl:DefineAlias "$site_5_0.mes38" "output_price_onway_work" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes38 \
        -in $site_5_0 -x 10 -y 10 -width 67 -height 15 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent123 \
        -in $site_4_0 -x 140 -y 40 -width 84 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent124 \
        -in $site_4_0 -x 140 -y 120 -width 84 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but125 \
        -in $site_4_0 -x 250 -y 40 -width 81 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but126 \
        -in $site_4_0 -x 250 -y 140 -width 81 -height 28 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra36 \
        -in $site_4_0 -x 28 -y 40 -width 85 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab36 \
        -in $site_4_0 -x 10 -y 110 -width 120 -height 53 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra37 \
        -in $site_4_0 -x 249 -y 100 -width 85 -height 35 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra97 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 195 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 185 
    vTcl:DefineAlias "$site_3_0.fra97" "Frame9" vTcl:WidgetProc "Console" 1
    set site_4_0 $site_3_0.fra97
    label $site_4_0.lab114 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 第一次 
    vTcl:DefineAlias "$site_4_0.lab114" "Label9" vTcl:WidgetProc "Console" 1
    label $site_4_0.lab115 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 第二次 
    vTcl:DefineAlias "$site_4_0.lab115" "Label10" vTcl:WidgetProc "Console" 1
    label $site_4_0.lab116 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 第三次 
    vTcl:DefineAlias "$site_4_0.lab116" "Label11" vTcl:WidgetProc "Console" 1
    frame $site_4_0.fra138 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 95 
    vTcl:DefineAlias "$site_4_0.fra138" "Frame15" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra138
    message $site_5_0.mes139 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 0 \
        -width 67 
    vTcl:DefineAlias "$site_5_0.mes139" "output_first_price" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes139 \
        -in $site_5_0 -x 10 -y 10 -width 67 -height 15 -anchor nw \
        -bordermode ignore 
    frame $site_4_0.fra140 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 95 
    vTcl:DefineAlias "$site_4_0.fra140" "Frame16" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra140
    message $site_5_0.mes142 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 0 \
        -width 67 
    vTcl:DefineAlias "$site_5_0.mes142" "output_second_price" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes142 \
        -in $site_5_0 -x 10 -y 10 -width 67 -height 15 -anchor nw \
        -bordermode ignore 
    frame $site_4_0.fra141 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 95 
    vTcl:DefineAlias "$site_4_0.fra141" "Frame17" vTcl:WidgetProc "Console" 1
    set site_5_0 $site_4_0.fra141
    message $site_5_0.mes143 \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text 0 \
        -width 67 
    vTcl:DefineAlias "$site_5_0.mes143" "output_third_price" vTcl:WidgetProc "Console" 1
    place $site_5_0.mes143 \
        -in $site_5_0 -x 10 -y 10 -width 67 -height 15 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab114 \
        -in $site_4_0 -x 10 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.lab115 \
        -in $site_4_0 -x 10 -y 90 -anchor nw -bordermode ignore 
    place $site_4_0.lab116 \
        -in $site_4_0 -x 10 -y 150 -anchor nw -bordermode ignore 
    place $site_4_0.fra138 \
        -in $site_4_0 -x 80 -y 20 -width 85 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra140 \
        -in $site_4_0 -x 80 -y 80 -width 85 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra141 \
        -in $site_4_0 -x 80 -y 140 -width 85 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra84 \
        -in $site_3_0 -x 230 -y 20 -width 345 -height 195 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra97 \
        -in $site_3_0 -x 20 -y 20 -width 185 -height 195 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra37 \
        -in $top -x 30 -y 30 -width 595 -height 145 -anchor nw \
        -bordermode ignore 
    place $top.fra39 \
        -in $top -x 30 -y 190 -width 595 -height 265 -anchor nw \
        -bordermode ignore 
    place $top.fra41 \
        -in $top -x 30 -y 470 -width 595 -height 235 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top36

