#############################################################################
# Generated by PAGE version 4.2.5
# in conjunction with Tcl version 8.6
#    May. 31, 2014 03:47:56 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#############################################################################
#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family 微软雅黑 -size 12 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top36
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 1
    }
    set site_3_0 $base.fra59
    set site_3_0 $base.fra68
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow. {base} {
    if {$base == ""} {
        set base .
    }
    ###################
    # CREATING WIDGETS
    ###################
    wm focusmodel $top passive
    wm geometry $top 200x200+150+150; update
    wm maxsize $top 1924 1062
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm withdraw $top
    wm title $top "page"
    bindtags $top "$top Page all"
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top36 {base} {
    if {$base == ""} {
        set base .top36
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 591x592+650+150; update
    wm maxsize $top 1924 1062
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Console"
    vTcl:DefineAlias "$top" "Console" vTcl:Toplevel:WidgetProc "" 1
    bindtags $top "$top Toplevel all _TopLevel"
    frame $top.fra59 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 245 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 505 
    vTcl:DefineAlias "$top.fra59" "frame_bid" vTcl:WidgetProc "Console" 1
    set site_3_0 $top.fra59
    button $site_3_0.but60 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} -font font12 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text 图片预热 
    vTcl:DefineAlias "$site_3_0.but60" "button_image_warmup" vTcl:WidgetProc "Console" 1
    bind $site_3_0.but60 <Button-1> {
        self.button_image_warmup_clicked
    }
    button $site_3_0.but61 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} -font font12 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text 价格预热 
    vTcl:DefineAlias "$site_3_0.but61" "button_price_warmup" vTcl:WidgetProc "Console" 1
    bind $site_3_0.but61 <Button-1> {
        self.button_price_warmup_clicked
    }
    entry $site_3_0.ent62 \
        -background white -disabledforeground {#a3a3a3} -font font12 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent62" "input_image_price" vTcl:WidgetProc "Console" 1
    entry $site_3_0.ent63 \
        -background white -disabledforeground {#a3a3a3} -font font12 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent63" "input_image_number" vTcl:WidgetProc "Console" 1
    button $site_3_0.but64 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} -font font12 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text 请求图形码 
    vTcl:DefineAlias "$site_3_0.but64" "button_image_price" vTcl:WidgetProc "Console" 1
    bind $site_3_0.but64 <Button-1> {
        self.button_image_price_clicked
    }
    button $site_3_0.but65 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} -font font12 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text 打码并出价 
    vTcl:DefineAlias "$site_3_0.but65" "button_image_number" vTcl:WidgetProc "Console" 1
    bind $site_3_0.but65 <Button-1> {
        self.button_image_number_clicked
    }
    label $site_3_0.lab66 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 价格 
    vTcl:DefineAlias "$site_3_0.lab66" "Label5" vTcl:WidgetProc "Console" 1
    label $site_3_0.lab67 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 图片 
    vTcl:DefineAlias "$site_3_0.lab67" "Label7" vTcl:WidgetProc "Console" 1
    place $site_3_0.but60 \
        -in $site_3_0 -x 120 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.but61 \
        -in $site_3_0 -x 280 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.ent62 \
        -in $site_3_0 -x 150 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.ent63 \
        -in $site_3_0 -x 150 -y 160 -anchor nw -bordermode ignore 
    place $site_3_0.but64 \
        -in $site_3_0 -x 380 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.but65 \
        -in $site_3_0 -x 380 -y 160 -anchor nw -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 70 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 70 -y 160 -anchor nw -bordermode ignore 
    frame $top.fra68 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 245 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 505 
    vTcl:DefineAlias "$top.fra68" "frame_server" vTcl:WidgetProc "Console" 1
    set site_3_0 $top.fra68
    entry $site_3_0.ent69 \
        -background white -disabledforeground {#a3a3a3} -font font12 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent69" "input_ip" vTcl:WidgetProc "Console" 1
    entry $site_3_0.ent70 \
        -background white -disabledforeground {#a3a3a3} -font font12 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent70" "input_port" vTcl:WidgetProc "Console" 1
    entry $site_3_0.ent71 \
        -background white -disabledforeground {#a3a3a3} -font font12 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent71" "input_bidno" vTcl:WidgetProc "Console" 1
    entry $site_3_0.ent72 \
        -background white -disabledforeground {#a3a3a3} -font font12 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent72" "input_passwd" vTcl:WidgetProc "Console" 1
    label $site_3_0.lab73 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 服务器IP 
    vTcl:DefineAlias "$site_3_0.lab73" "Label1" vTcl:WidgetProc "Console" 1
    label $site_3_0.lab74 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 服务器Port 
    vTcl:DefineAlias "$site_3_0.lab74" "Label2" vTcl:WidgetProc "Console" 1
    label $site_3_0.lab75 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 用户账号 
    vTcl:DefineAlias "$site_3_0.lab75" "Label3" vTcl:WidgetProc "Console" 1
    label $site_3_0.lab76 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 用户密码 
    vTcl:DefineAlias "$site_3_0.lab76" "Label4" vTcl:WidgetProc "Console" 1
    label $site_3_0.lab77 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -borderwidth 5 -disabledforeground {#a3a3a3} \
        -font font12 -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 最新信息 
    vTcl:DefineAlias "$site_3_0.lab77" "Label8" vTcl:WidgetProc "Console" 1
    button $site_3_0.but78 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} -font font12 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text 连接服务器 
    vTcl:DefineAlias "$site_3_0.but78" "button_connect" vTcl:WidgetProc "Console" 1
    bind $site_3_0.but78 <Button-1> {
        self.button_connect_clicked
    }
    place $site_3_0.ent69 \
        -in $site_3_0 -x 110 -y 30 -anchor nw -bordermode ignore 
    place $site_3_0.ent70 \
        -in $site_3_0 -x 110 -y 80 -anchor nw -bordermode ignore 
    place $site_3_0.ent71 \
        -in $site_3_0 -x 110 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.ent72 \
        -in $site_3_0 -x 110 -y 180 -anchor nw -bordermode ignore 
    place $site_3_0.lab73 \
        -in $site_3_0 -x 30 -y 30 -anchor nw -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 30 -y 80 -anchor nw -bordermode ignore 
    place $site_3_0.lab75 \
        -in $site_3_0 -x 30 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.lab76 \
        -in $site_3_0 -x 30 -y 180 -anchor nw -bordermode ignore 
    place $site_3_0.lab77 \
        -in $site_3_0 -x 320 -y 30 -width 167 -height 83 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but78 \
        -in $site_3_0 -x 360 -y 150 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra59 \
        -in $top -x 40 -y 310 -width 505 -height 245 -anchor nw \
        -bordermode ignore 
    place $top.fra68 \
        -in $top -x 40 -y 30 -width 505 -height 245 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top36

