
use pp_origin;

CREATE TABLE IF NOT EXISTS format_origin_2014_07_26(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, info TEXT, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_origin_2014_06_29(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, info TEXT, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_origin_2014_06_21(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, info TEXT, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_origin_2014_05_24(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, info TEXT, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_origin_2014_04_19(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, info TEXT, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_origin_2014_03_15(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, info TEXT, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_origin_2014_02_15(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, info TEXT, INDEX(datetime)) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS format_origin_2014_01_18(sn INT PRIMARY KEY AUTO_INCREMENT, datetime DATETIME, info TEXT, INDEX(datetime)) DEFAULT CHARSET=utf8;

